# Generated by Django 5.2 on 2025-04-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='age',
            field=models.CharField(default='16 weeks', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puppy',
            name='gender',
            field=models.CharField(default='Female', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puppy',
            name='registration',
            field=models.CharField(default='AKC', max_length=255),
            preserve_default=False,
        ),
    ]
