# Generated by Django 5.2 on 2025-04-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_puppy_age_puppy_gender_puppy_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='age',
            field=models.PositiveBigIntegerField(),
        ),
    ]
